/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_HW5SERVER_H_
#define JSONRPC_CPP_STUB_HW5SERVER_H_

#include <jsonrpccpp/server.h>

class hw5Server : public jsonrpc::AbstractServer<hw5Server>
{
    public:
        hw5Server(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<hw5Server>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("move", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "action",jsonrpc::JSON_STRING,"class_id",jsonrpc::JSON_STRING,"json_object",jsonrpc::JSON_OBJECT,"location",jsonrpc::JSON_OBJECT,"object_id",jsonrpc::JSON_STRING, NULL), &hw5Server::moveI);
            this->bindAndAddMethod(jsonrpc::Procedure("done", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &hw5Server::doneI);
            this->bindAndAddMethod(jsonrpc::Procedure("obtain", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "action",jsonrpc::JSON_STRING,"class_id",jsonrpc::JSON_STRING,"object_id",jsonrpc::JSON_STRING, NULL), &hw5Server::obtainI);
            this->bindAndAddMethod(jsonrpc::Procedure("insert", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "action",jsonrpc::JSON_STRING,"key",jsonrpc::JSON_STRING,"moto",jsonrpc::JSON_OBJECT, NULL), &hw5Server::insertI);
        }

        inline virtual void moveI(const Json::Value &request, Json::Value &response)
        {
            response = this->move(request["action"].asString(), request["class_id"].asString(), request["json_object"], request["location"], request["object_id"].asString());
        }
        inline virtual void doneI(const Json::Value &/*request*/, Json::Value &response)
        {
            response = this->done();
        }
        inline virtual void obtainI(const Json::Value &request, Json::Value &response)
        {
            response = this->obtain(request["action"].asString(), request["class_id"].asString(), request["object_id"].asString());
        }
        inline virtual void insertI(const Json::Value &request, Json::Value &response)
        {
            response = this->insert(request["action"].asString(), request["key"].asString(), request["moto"]);
        }
        virtual Json::Value move(const std::string& action, const std::string& class_id, const Json::Value& json_object, const Json::Value& location, const std::string& object_id) = 0;
        virtual Json::Value done() = 0;
        virtual Json::Value obtain(const std::string& action, const std::string& class_id, const std::string& object_id) = 0;
        virtual Json::Value insert(const std::string& action, const std::string& key, const Json::Value& moto) = 0;
};

#endif //JSONRPC_CPP_STUB_HW5SERVER_H_
